name: Metrics
on:
  # Update every 12 hours
  schedule: [{cron: "0 */12 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to main/master branches
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub Personal Access Token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic configuration
          user: mysteriza
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          
          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_main: yes
